//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyNhanSuEntities : DbContext
    {
        public QuanLyNhanSuEntities()
            : base("name=QuanLyNhanSuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBangCong> tblBangCongs { get; set; }
        public virtual DbSet<tblBaoHiem> tblBaoHiems { get; set; }
        public virtual DbSet<tblBoPhan> tblBoPhans { get; set; }
        public virtual DbSet<tblChucVu> tblChucVus { get; set; }
        public virtual DbSet<tblCongTy> tblCongTies { get; set; }
        public virtual DbSet<tblDanToc> tblDanTocs { get; set; }
        public virtual DbSet<tblDieuChuyen> tblDieuChuyens { get; set; }
        public virtual DbSet<tblHopDong> tblHopDongs { get; set; }
        public virtual DbSet<tblKhenThuong_KyLuat> tblKhenThuong_KyLuat { get; set; }
        public virtual DbSet<tblKyLuat_NV> tblKyLuat_NV { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblNhanVien_NangLuong> tblNhanVien_NangLuong { get; set; }
        public virtual DbSet<tblNhanVien_PhuCap> tblNhanVien_PhuCap { get; set; }
        public virtual DbSet<tblPhongBan> tblPhongBans { get; set; }
        public virtual DbSet<tblPhuCap> tblPhuCaps { get; set; }
        public virtual DbSet<tblTangCa> tblTangCas { get; set; }
        public virtual DbSet<tblThoiViec> tblThoiViecs { get; set; }
        public virtual DbSet<tblTonGiao> tblTonGiaos { get; set; }
        public virtual DbSet<tblTrinhDo> tblTrinhDoes { get; set; }
        public virtual DbSet<tblUngLuong> tblUngLuongs { get; set; }
        public virtual DbSet<tblLoaiCa> tblLoaiCas { get; set; }
        public virtual DbSet<tblLoaiCong> tblLoaiCongs { get; set; }
        public virtual DbSet<tblBANGCONG_NHANVIEN_CHITIET> tblBANGCONG_NHANVIEN_CHITIET { get; set; }
        public virtual DbSet<tblKYCONG> tblKYCONGs { get; set; }
        public virtual DbSet<tblKYCONGCHITIET> tblKYCONGCHITIETs { get; set; }
    }
}
