//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien_NangLuong
    {
        public string SoQuyetDinh { get; set; }
        public string SoHopDong { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<double> HeSoLuongHienTai { get; set; }
        public Nullable<double> HeSoLuogMoi { get; set; }
        public Nullable<System.DateTime> NgayLenLuong { get; set; }
        public Nullable<System.DateTime> NgayKi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Creared_Date { get; set; }
        public Nullable<int> Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
