//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.tblBangCongs = new HashSet<tblBangCong>();
            this.tblBaoHiems = new HashSet<tblBaoHiem>();
            this.tblDieuChuyens = new HashSet<tblDieuChuyen>();
            this.tblHopDongs = new HashSet<tblHopDong>();
            this.tblKhenThuong_KyLuat = new HashSet<tblKhenThuong_KyLuat>();
            this.tblKyLuat_NV = new HashSet<tblKyLuat_NV>();
            this.tblNhanVien_NangLuong = new HashSet<tblNhanVien_NangLuong>();
            this.tblNhanVien_PhuCap = new HashSet<tblNhanVien_PhuCap>();
            this.tblTangCas = new HashSet<tblTangCa>();
            this.tblThoiViecs = new HashSet<tblThoiViec>();
            this.tblUngLuongs = new HashSet<tblUngLuong>();
        }
    
        public int MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DienThoai { get; set; }
        public string CCCD { get; set; }
        public string DiaChi { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<int> IDPhongBan { get; set; }
        public Nullable<int> IDBoPhan { get; set; }
        public Nullable<int> IDChucVu { get; set; }
        public Nullable<int> IDTrinhDo { get; set; }
        public Nullable<int> IDDanToc { get; set; }
        public Nullable<int> IDTonGiao { get; set; }
        public Nullable<int> IDCongTy { get; set; }
        public Nullable<bool> DaThoiViec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBangCong> tblBangCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBaoHiem> tblBaoHiems { get; set; }
        public virtual tblBoPhan tblBoPhan { get; set; }
        public virtual tblChucVu tblChucVu { get; set; }
        public virtual tblCongTy tblCongTy { get; set; }
        public virtual tblDanToc tblDanToc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDieuChuyen> tblDieuChuyens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHopDong> tblHopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKhenThuong_KyLuat> tblKhenThuong_KyLuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKyLuat_NV> tblKyLuat_NV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhanVien_NangLuong> tblNhanVien_NangLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNhanVien_PhuCap> tblNhanVien_PhuCap { get; set; }
        public virtual tblPhongBan tblPhongBan { get; set; }
        public virtual tblTonGiao tblTonGiao { get; set; }
        public virtual tblTrinhDo tblTrinhDo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTangCa> tblTangCas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblThoiViec> tblThoiViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUngLuong> tblUngLuongs { get; set; }
    }
}
