//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPlayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTangCa
    {
        public int ID { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Ngay { get; set; }
        public Nullable<double> SoGio { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> IDLoaiCa { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblLoaiCa tblLoaiCa { get; set; }
    }
}
